# =====================================================
# Single White Controller (1 Kanal: Dimmer)
# ESPHome RGBWW Controller - Dimmer Variant
# Version: 2.0 - Working with proper color_mode control
# =====================================================

esphome:
  name: white-dimmer
  comment: "Single White LED Dimmer Controller"
  project:
    name: vr6syncro.esphome-rgbww-controller
    version: "2.0-dimmer"

# Restore nach Power Loss
preferences:
  flash_write_interval: 30s

# Platform
esp8266:
  board: esp12e
  restore_from_flash: true

# Logging
logger:
  level: INFO

# Services
api:
  encryption:
    key: !secret api_encryption_key
  reboot_timeout: 0s

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

captive_portal:

# Status LED
status_led:
  pin: GPIO2

# =====================
# Single Output (1 Kanal)
# =====================
output:
  - platform: esp8266_pwm
    id: out_white
    pin: GPIO5
    frequency: 1200 Hz

# =====================
# Monochromatic Light (Dimmer)
# =====================
light:
  - platform: monochromatic
    name: "White Dimmer"
    id: white_dimmer
    output: out_white
    gamma_correct: 2.8
    default_transition_length: 800ms
    restore_mode: RESTORE_DEFAULT_OFF
    effects:
      - pulse:
          name: "Soft Pulse"
          transition_length: 2s
      - flicker:
          name: "Candle"
          alpha: 95%
          intensity: 1.5%

# =====================
# Presets
# =====================
button:
  # --- BRIGHTNESS PRESETS ---
  - platform: template
    id: preset_100_percent
    name: "Preset: 100%"
    icon: mdi:lightbulb-on
    on_press:
      - light.control:
          id: white_dimmer
          brightness: 100%

  - platform: template
    id: preset_75_percent
    name: "Preset: 75%"
    icon: mdi:lightbulb-on-outline
    on_press:
      - light.control:
          id: white_dimmer
          brightness: 75%

  - platform: template
    id: preset_50_percent
    name: "Preset: 50%"
    icon: mdi:lightbulb-on-outline
    on_press:
      - light.control:
          id: white_dimmer
          brightness: 50%

  - platform: template
    id: preset_25_percent
    name: "Preset: 25%"
    icon: mdi:lightbulb-outline
    on_press:
      - light.control:
          id: white_dimmer
          brightness: 25%

  # --- SCENE PRESETS ---
  - platform: template
    id: preset_night_light
    name: "Preset: Night Light"
    icon: mdi:weather-night
    on_press:
      - light.control:
          id: white_dimmer
          brightness: 10%

  - platform: template
    id: preset_reading
    name: "Preset: Reading"
    icon: mdi:book-open-page-variant
    on_press:
      - light.control:
          id: white_dimmer
          brightness: 60%

  - platform: template
    id: preset_relax
    name: "Preset: Relax"
    icon: mdi:sofa
    on_press:
      - light.control:
          id: white_dimmer
          brightness: 30%
          transition_length: 3s

  - platform: template
    id: preset_wake_up
    name: "Preset: Wake Up"
    icon: mdi:weather-sunset-up
    on_press:
      - light.control:
          id: white_dimmer
          brightness: 100%
          transition_length: 30s

  - platform: safe_mode
    name: "Safe Mode"

  - platform: factory_reset
    name: "Factory Reset"

  - platform: restart
    name: "Restart Controller"

# =====================
# Sensors
# =====================
sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "Uptime"

binary_sensor:
  - platform: status
    name: "Online"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    ssid:
      name: "SSID"
    mac_address:
      name: "MAC"