# =====================================================
# RGBWW Controller (5 Kanäle: R, G, B, WW, CW)
# ESPHome RGBWW Controller - Full Featured Variant
# Version: 2.0 - Working with proper color_mode control
# =====================================================

esphome:
  name: rgbww-controller
  comment: "RGBWW LED Controller - Full with Presets and Scenes"
  project:
    name: vr6syncro.esphome-rgbww-controller
    version: "2.0"

preferences:
  flash_write_interval: 30s

esp8266:
  board: esp12e
  restore_from_flash: true

logger:
  level: INFO

api:
  encryption:
    key: !secret api_encryption_key
  reboot_timeout: 0s

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

status_led:
  pin: GPIO2

# ---------------------
# Outputs
# ---------------------
output:
  - platform: esp8266_pwm
    id: out_red
    pin: GPIO13
    frequency: 1200 Hz
  - platform: esp8266_pwm
    id: out_green
    pin: GPIO12
    frequency: 1200 Hz
  - platform: esp8266_pwm
    id: out_blue
    pin: GPIO14
    frequency: 1200 Hz
  - platform: esp8266_pwm
    id: out_warm_white
    pin: GPIO5
    frequency: 1200 Hz
  - platform: esp8266_pwm
    id: out_cold_white
    pin: GPIO4
    frequency: 1200 Hz

# ---------------------
# Main Light
# ---------------------
light:
  - platform: rgbww
    name: "RGBWW Strip"
    id: rgbww_light
    red: out_red
    green: out_green
    blue: out_blue
    warm_white: out_warm_white
    cold_white: out_cold_white
    cold_white_color_temperature: 6000 K
    warm_white_color_temperature: 2700 K
    gamma_correct: 2.8
    default_transition_length: 800ms
    constant_brightness: false
    color_interlock: true
    restore_mode: RESTORE_DEFAULT_OFF
    effects:
      - pulse:
          name: "Soft Pulse"
          transition_length: 1.5s
      - random:
          name: "Random Colors"
          transition_length: 2s
      - flicker:
          name: "Candle"
          alpha: 95%
          intensity: 1.5%

# ---------------------
# Presets / Scenes
# ---------------------
button:
  # --- RGB COLORS ---
  - platform: template
    id: preset_red
    name: "Preset: Red"
    icon: mdi:led-strip-variant
    on_press:
      - light.control:
          id: rgbww_light
          color_mode: RGB
          brightness: !lambda return id(rgbww_light).current_values.get_brightness();
          red: 100%
          green: 0%
          blue: 0%

  - platform: template
    id: preset_green
    name: "Preset: Green"
    icon: mdi:led-strip-variant
    on_press:
      - light.control:
          id: rgbww_light
          color_mode: RGB
          brightness: !lambda return id(rgbww_light).current_values.get_brightness();
          red: 0%
          green: 100%
          blue: 0%

  - platform: template
    id: preset_blue
    name: "Preset: Blue"
    icon: mdi:led-strip-variant
    on_press:
      - light.control:
          id: rgbww_light
          color_mode: RGB
          brightness: !lambda return id(rgbww_light).current_values.get_brightness();
          red: 0%
          green: 0%
          blue: 100%

  - platform: template
    id: preset_yellow
    name: "Preset: Yellow"
    icon: mdi:led-strip-variant
    on_press:
      - light.control:
          id: rgbww_light
          color_mode: RGB
          brightness: !lambda return id(rgbww_light).current_values.get_brightness();
          red: 100%
          green: 100%
          blue: 0%

  - platform: template
    id: preset_cyan
    name: "Preset: Cyan"
    icon: mdi:led-strip-variant
    on_press:
      - light.control:
          id: rgbww_light
          color_mode: RGB
          brightness: !lambda return id(rgbww_light).current_values.get_brightness();
          red: 0%
          green: 100%
          blue: 100%

  - platform: template
    id: preset_purple
    name: "Preset: Purple"
    icon: mdi:led-strip-variant
    on_press:
      - light.control:
          id: rgbww_light
          color_mode: RGB
          brightness: !lambda return id(rgbww_light).current_values.get_brightness();
          red: 100%
          green: 0%
          blue: 100%

  # --- WHITE TEMPERATURES ---
  - platform: template
    id: preset_warm_white_2700k
    name: "Preset: Warm White 2700K"
    icon: mdi:lightbulb-on
    on_press:
      - light.control:
          id: rgbww_light
          color_mode: COLD_WARM_WHITE
          color_temperature: 2700 K
          brightness: !lambda return id(rgbww_light).current_values.get_brightness();

  - platform: template
    id: preset_neutral_white_4000k
    name: "Preset: Neutral White 4000K"
    icon: mdi:lightbulb-variant
    on_press:
      - light.control:
          id: rgbww_light
          color_mode: COLD_WARM_WHITE
          color_temperature: 4000 K
          brightness: !lambda return id(rgbww_light).current_values.get_brightness();

  - platform: template
    id: preset_cool_white_6000k
    name: "Preset: Cool White 6000K"
    icon: mdi:snowflake
    on_press:
      - light.control:
          id: rgbww_light
          color_mode: COLD_WARM_WHITE
          color_temperature: 6000 K
          brightness: !lambda return id(rgbww_light).current_values.get_brightness();

  # --- SCENES ---
  - platform: template
    id: preset_reading_light
    name: "Preset: Reading Light"
    icon: mdi:book-open-page-variant
    on_press:
      - light.control:
          id: rgbww_light
          color_mode: COLD_WARM_WHITE
          color_temperature: 3200 K
          brightness: !lambda return id(rgbww_light).current_values.get_brightness();

  - platform: template
    id: preset_office_light
    name: "Preset: Office Light"
    icon: mdi:briefcase
    on_press:
      - light.control:
          id: rgbww_light
          color_mode: COLD_WARM_WHITE
          color_temperature: 5500 K
          brightness: !lambda return id(rgbww_light).current_values.get_brightness();

  - platform: template
    id: preset_relax
    name: "Preset: Relax"
    icon: mdi:sofa
    on_press:
      - light.control:
          id: rgbww_light
          color_mode: COLD_WARM_WHITE
          color_temperature: 3000 K
          brightness: !lambda return id(rgbww_light).current_values.get_brightness();

  - platform: template
    id: preset_night_light
    name: "Preset: Night Light"
    icon: mdi:weather-night
    on_press:
      - light.control:
          id: rgbww_light
          color_mode: COLD_WARM_WHITE
          color_temperature: 2700 K
          brightness: !lambda return id(rgbww_light).current_values.get_brightness();

  - platform: template
    id: preset_candle
    name: "Preset: Candle"
    icon: mdi:candle
    on_press:
      - light.control:
          id: rgbww_light
          color_mode: RGB
          effect: Candle
          brightness: !lambda return id(rgbww_light).current_values.get_brightness();
          red: 100%
          green: 60%
          blue: 10%

  # --- System ---
  - platform: restart
    id: restart_controller
    name: "Restart Controller"

# ---------------------
# Sensors
# ---------------------
sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "Uptime"

binary_sensor:
  - platform: status
    name: "Online"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    ssid:
      name: "SSID"
    mac_address:
      name: "MAC"