# =====================================================
# Dual White Controller (2 Kanäle: WW, CW)
# ESPHome RGBWW Controller - CCT Variant
# Version: 2.1
# =====================================================

esphome:
  name: dual-white-controller
  comment: "Dual White CCT LED Controller - 2 Channel"
  project:
    name: vr6syncro.esphome-rgbww-controller
    version: "2.1-cct"

# Restore nach Power Loss
preferences:
  flash_write_interval: 30s

# Platform
esp8266:
  board: esp12e
  restore_from_flash: true

# Logging
logger:
  level: INFO

# Services
api:
  encryption:
    key: !secret api_encryption_key
  reboot_timeout: 0s

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

captive_portal:

# Status LED
status_led:
  pin: GPIO2

# =====================
# Dual White Outputs (2 Kanäle)
# =====================
output:
  - platform: esp8266_pwm
    id: out_warm_white
    pin: GPIO5
    frequency: 1200 Hz
  - platform: esp8266_pwm
    id: out_cold_white
    pin: GPIO4
    frequency: 1200 Hz

# =====================
# Color Temperature Light (CCT)
# =====================
light:
  - platform: cwww
    name: "CCT Strip"
    id: cct_light
    warm_white: out_warm_white
    cold_white: out_cold_white
    cold_white_color_temperature: 6000 K
    warm_white_color_temperature: 2700 K
    gamma_correct: 2.8
    default_transition_length: 800ms
    constant_brightness: true
    restore_mode: RESTORE_DEFAULT_OFF
    effects:
      - pulse:
          name: "Soft Pulse"
          transition_length: 2s
      - flicker:
          name: "Candle"
          alpha: 95%
          intensity: 1.5%

# =====================
# Presets (Dashboard-Kompatibel)
# =====================
button:
  # --- COLOR TEMPERATURE PRESETS ---
  - platform: template
    id: preset_warm_2700k
    name: "Preset: Warm 2700K"
    icon: mdi:white-balance-sunny
    on_press:
      - light.control:
          id: cct_light
          color_mode: COLD_WARM_WHITE
          color_temperature: 2700 K
          brightness: !lambda return id(cct_light).current_values.get_brightness();

  - platform: template
    id: preset_warm_3000k
    name: "Preset: Warm 3000K"
    icon: mdi:white-balance-sunny
    on_press:
      - light.control:
          id: cct_light
          color_mode: COLD_WARM_WHITE
          color_temperature: 3000 K
          brightness: !lambda return id(cct_light).current_values.get_brightness();

  - platform: template
    id: preset_neutral_4000k
    name: "Preset: Neutral 4000K"
    icon: mdi:lightbulb-variant
    on_press:
      - light.control:
          id: cct_light
          color_mode: COLD_WARM_WHITE
          color_temperature: 4000 K
          brightness: !lambda return id(cct_light).current_values.get_brightness();

  - platform: template
    id: preset_cool_5000k
    name: "Preset: Cool 5000K"
    icon: mdi:snowflake-variant
    on_press:
      - light.control:
          id: cct_light
          color_mode: COLD_WARM_WHITE
          color_temperature: 5000 K
          brightness: !lambda return id(cct_light).current_values.get_brightness();

  - platform: template
    id: preset_cool_6000k
    name: "Preset: Cool 6000K"
    icon: mdi:snowflake
    on_press:
      - light.control:
          id: cct_light
          color_mode: COLD_WARM_WHITE
          color_temperature: 6000 K
          brightness: !lambda return id(cct_light).current_values.get_brightness();

  # --- SCENE PRESETS ---
  - platform: template
    id: preset_morning
    name: "Preset: Morning"
    icon: mdi:weather-sunset-up
    on_press:
      - light.control:
          id: cct_light
          color_mode: COLD_WARM_WHITE
          color_temperature: 3500 K
          brightness: 80%

  - platform: template
    id: preset_office
    name: "Preset: Office"
    icon: mdi:briefcase
    on_press:
      - light.control:
          id: cct_light
          color_mode: COLD_WARM_WHITE
          color_temperature: 5000 K
          brightness: 90%

  - platform: template
    id: preset_reading
    name: "Preset: Reading"
    icon: mdi:book-open-page-variant
    on_press:
      - light.control:
          id: cct_light
          color_mode: COLD_WARM_WHITE
          color_temperature: 4000 K
          brightness: 85%

  - platform: template
    id: preset_relax
    name: "Preset: Relax"
    icon: mdi:sofa
    on_press:
      - light.control:
          id: cct_light
          color_mode: COLD_WARM_WHITE
          color_temperature: 3000 K
          brightness: 30%
          transition_length: 3s

  - platform: template
    id: preset_night_light
    name: "Preset: Night Light"
    icon: mdi:weather-night
    on_press:
      - light.control:
          id: cct_light
          color_mode: COLD_WARM_WHITE
          color_temperature: 2700 K
          brightness: 5%

  - platform: safe_mode
    name: "Safe Mode"

  - platform: factory_reset
    name: "Factory Reset"

  - platform: restart
    name: "Restart Controller"

# =====================
# Sensors
# =====================
sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "Uptime"

binary_sensor:
  - platform: status
    name: "Online"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    ssid:
      name: "SSID"
    mac_address:
      name: "MAC"