# =====================================================
# RGB Controller (3 Kanäle: R, G, B)
# ESPHome RGBWW Controller - RGB Variant
# Version: 2.0 - Working with proper color_mode control
# =====================================================

esphome:
  name: rgb-controller
  comment: "RGB LED Controller - 3 Channel with Color Presets"
  project:
    name: vr6syncro.esphome-rgbww-controller
    version: "2.0-rgb"

preferences:
  flash_write_interval: 30s

esp8266:
  board: esp12e
  restore_from_flash: true

logger:
  level: INFO

api:
  encryption:
    key: !secret api_encryption_key
  reboot_timeout: 0s

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

status_led:
  pin: GPIO2

# ---------------------
# Outputs
# ---------------------
output:
  - platform: esp8266_pwm
    id: out_red
    pin: GPIO13
    frequency: 1200 Hz
  - platform: esp8266_pwm
    id: out_green
    pin: GPIO12
    frequency: 1200 Hz
  - platform: esp8266_pwm
    id: out_blue
    pin: GPIO14
    frequency: 1200 Hz

# ---------------------
# Main Light
# ---------------------
light:
  - platform: rgb
    name: "RGB Strip"
    id: rgb_light
    red: out_red
    green: out_green
    blue: out_blue
    gamma_correct: 2.8
    default_transition_length: 800ms
    restore_mode: RESTORE_DEFAULT_OFF
    effects:
      - pulse:
          name: "Soft Pulse"
          transition_length: 1.5s
      - random:
          name: "Random Colors"
          transition_length: 2s
      - flicker:
          name: "Candle"
          alpha: 95%
          intensity: 1.5%

# ---------------------
# Presets / Scenes
# ---------------------
button:
  # --- RGB COLORS ---
  - platform: template
    id: preset_red
    name: "Preset: Red"
    icon: mdi:led-strip-variant
    on_press:
      - light.control:
          id: rgb_light
          brightness: !lambda return id(rgb_light).current_values.get_brightness();
          red: 100%
          green: 0%
          blue: 0%

  - platform: template
    id: preset_green
    name: "Preset: Green"
    icon: mdi:led-strip-variant
    on_press:
      - light.control:
          id: rgb_light
          brightness: !lambda return id(rgb_light).current_values.get_brightness();
          red: 0%
          green: 100%
          blue: 0%

  - platform: template
    id: preset_blue
    name: "Preset: Blue"
    icon: mdi:led-strip-variant
    on_press:
      - light.control:
          id: rgb_light
          brightness: !lambda return id(rgb_light).current_values.get_brightness();
          red: 0%
          green: 0%
          blue: 100%

  - platform: template
    id: preset_yellow
    name: "Preset: Yellow"
    icon: mdi:led-strip-variant
    on_press:
      - light.control:
          id: rgb_light
          brightness: !lambda return id(rgb_light).current_values.get_brightness();
          red: 100%
          green: 100%
          blue: 0%

  - platform: template
    id: preset_cyan
    name: "Preset: Cyan"
    icon: mdi:led-strip-variant
    on_press:
      - light.control:
          id: rgb_light
          brightness: !lambda return id(rgb_light).current_values.get_brightness();
          red: 0%
          green: 100%
          blue: 100%

  - platform: template
    id: preset_purple
    name: "Preset: Purple"
    icon: mdi:led-strip-variant
    on_press:
      - light.control:
          id: rgb_light
          brightness: !lambda return id(rgb_light).current_values.get_brightness();
          red: 100%
          green: 0%
          blue: 100%

  # --- WHITE SIMULATIONS (RGB MIX) ---
  - platform: template
    id: preset_white_rgb
    name: "Preset: White (RGB)"
    icon: mdi:lightbulb
    on_press:
      - light.control:
          id: rgb_light
          brightness: !lambda return id(rgb_light).current_values.get_brightness();
          red: 100%
          green: 100%
          blue: 100%

  - platform: template
    id: preset_warm_white_rgb
    name: "Preset: Warm White (RGB)"
    icon: mdi:lightbulb-on
    on_press:
      - light.control:
          id: rgb_light
          brightness: !lambda return id(rgb_light).current_values.get_brightness();
          red: 100%
          green: 83%
          blue: 66%

  - platform: template
    id: preset_cool_white_rgb
    name: "Preset: Cool White (RGB)"
    icon: mdi:snowflake
    on_press:
      - light.control:
          id: rgb_light
          brightness: !lambda return id(rgb_light).current_values.get_brightness();
          red: 95%
          green: 100%
          blue: 100%

  # --- SCENES ---
  - platform: template
    id: preset_candle
    name: "Preset: Candle"
    icon: mdi:candle
    on_press:
      - light.control:
          id: rgb_light
          effect: Candle
          brightness: !lambda return id(rgb_light).current_values.get_brightness();
          red: 100%
          green: 60%
          blue: 10%

  # --- System ---
  - platform: restart
    id: restart_controller
    name: "Restart Controller"

# ---------------------
# Sensors
# ---------------------
sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "Uptime"

binary_sensor:
  - platform: status
    name: "Online"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    ssid:
      name: "SSID"
    mac_address:
      name: "MAC"